### ISSUE TITLE
Entity implements device_state_attributes

### ISSUE THREAD

**Issue by BugBasher28** [skagmo/ha_vwid#22]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:580
First occurred: 15:31:42 (1 occurrences)
Last logged: 15:31:42

Entity sensor.mycar_soc (<class 'custom_components.vwid.sensor.VwidSensor'>) implements device_state_attributes. Please report it to the custom component author.

-----
I have no idea what this means but it's in my logs. And now I have reported it.

**Comment by jcsogo** [comment]
This means that the integration should use the extra_state_attributes instead of device_state_attributes which has been deprecated. 

[https://developers.home-assistant.io/docs/core/entity/?_highlight=extra_state_attributes#generic-properties](https://developers.home-assistant.io/docs/core/entity/?_highlight=extra_state_attributes#generic-properties)

**Comment by skagmo** [comment]
Thanks for giving me a heads up about this. Apparently device_state_attributes stopped working in 2022.4. Fixed in commit a039e92.
