### ISSUE TITLE
Component stopped working

### ISSUE THREAD

**Issue by lorddaku** [skagmo/ha_vwid#6]
HA Version:

Version | core-2021.5.5
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.9
Operating System Family | Linux
Operating System Version | 4.19.0-16-amd64
CPU Architecture | x86_64
Timezone | Europe/Stockholm

LOGS:

Logger: custom_components.vwid.sensor
Source: /config/custom_components/vwid/sensor.py:111
Integration: Volkswagen ID (documentation) 
First occurred: 3 juni 2021 18:22:24 (308 occurrences) 
Last logged: 21:32:26

Error retrieving data

##
Logger: custom_components.vwid.libvwid
Source: custom_components/vwid/libvwid.py:141 
Integration: Volkswagen ID (documentation) 
First occurred: 3 juni 2021 18:22:24 (308 occurrences) 
Last logged: 21:32:26

Get status failed
##
Logger: custom_components.vwid.libvwid
Source: custom_components/vwid/libvwid.py:79 
Integration: Volkswagen ID (documentation) 
First occurred: 3 juni 2021 18:22:24 (308 occurrences) 
Last logged: 21:32:26

Not redirected

**Comment by superharaldsson** [comment]
The same for me!
Both in core-2021.6.3 and core-2021.5.5.

**Comment by skagmo** [comment]
I'll have a look at it one day.

Keep in mind this is the errors you'll see for any kind of connectivity issue: Server rejecting connection, server/internet connection down, wrong password etc. It could definitely be nice to have the component log more specific errors.

I had these errors for almost a full day. I'm that case the issue was the VW servers being down. (They have pretty bad uptime.)

**Comment by rgilijamse** [comment]
It looks like the problem is on the API side, not on the Home Assistant side. I get the same errors when running `libvwid_example.py` directly:

```
INFO:libvwid:Reconnecting
ERROR:libvwid:Not redirected
ERROR:libvwid:Get status failed

```
It looks like the authentication returns HTTP 303 where the code expects HTTP 302, and throws the "Not redirected" error. I can't tell if this is a transient problem or if the authentication process has actually changed.

**Comment by skagmo** [comment]
Hi. Had a look at this yesterday, and there seems to be an extra step in logging in now. Terms and conditions have to be accepted before login is completed. I'll have a look at how this can be solved.

**Comment by skagmo** [comment]
Please try the latest commit.

**Comment by superharaldsson** [comment]
Works great. 
Thanks 👍

**Comment by skagmo** [comment]
Good to hear, thanks for the quick feedback!
